### PR TITLE
Docs/improvements

### PR DESCRIPTION
**Pull request by LucaMarconato**
In this PR (ready to merge):
- I fixed all the warnings that the docs generation was making;
- I improved the aesthetics of the docs (asked by Oli).

More on the aesthetics:
- I added an icon on the top left of the docs
- I changed the theme from `sphinx_book_theme` to `sphinx_rtd_theme`. I think that the latter is graphically more pleasant (see also screenshots).

Not in this PR:
- I checked how much work it would be to make a gallery of icons for the vignette (like in squidpy). It's like a few hours of work, but I think we should do this with low priority (after all the notebooks are up). I created this issue to keep track of the progress https://github.com/scverse/spatialdata/issues/205.

### CODE REVIEW

**Comment by LucaMarconato** [comment]
`sphinx_book_theme`

Screenshot 2023-04-04 at 01 05 24

**Comment by LucaMarconato** [comment]
`sphinx_rtd_theme`
image

**Comment by LucaMarconato** [comment]
Todo: change the theme to `sphinx-book`

**Review by giovp — APPROVED** [review]

**Comment by LucaMarconato** [comment]
@giovp I reverted to the shpinx-book theme, the only thing to fix is the content tree aesthetics as discussed. As mentioned in the spatialdata-notebooks pr, I would keep the icons for the gallery as it is now and improve later.

Please merge https://github.com/scverse/spatialdata-notebooks/pull/11 first.

**Pull request merged**
