### PR TITLE
Fix channel names in transform for MultiscaleSpatialImage

### PR DESCRIPTION
**Pull request by aeisenbarth**
When transforming a MultiscaleSpatialImage, a KeyError is raised. See https://github.com/scverse/spatialdata/issues/378

So far, I've modified the test case to cover both SpatialImage and MultiscaleSpatialImage and reproduce the problem. I have no proposed fix yet.

### CODE REVIEW

**Comment by giovp** [comment]
I think this can be closed right?

**Comment by aeisenbarth** [comment]
I rebased onto main and the KeyError does not occur anymore.

However, the second test case fails because it gets only integer channel names instead of string channel names. It seems the string values get lost by `transform` if it transforms a multi-channel image.

**Comment by aeisenbarth** [comment]
Yes, the changes look good!

**Review by melonora — APPROVED** [review]
Thanks it looks good to me. Minor comment, we don't have to do `.images[name_element]` anymore. I usually prefer it as short as possible, but no blocker:)

**Comment by giovp** [comment]
> we don't have to do .images[name_element] anymore

true but I think people still use it (I do) ? also is just for the tests

**Comment by giovp** [comment]
@aeisenbarth could you write a very small note for release? then we can merge, thank you!

**Comment by melonora** [comment]
> > we don't have to do .images[name_element] anymore
> 
> true but I think people still use it (I do) ? also is just for the tests

yeah like I said for me personal preference, but non-blocking:)

**Comment by melonora** [comment]
Thanks Andreas!

**Pull request merged**
