### PR TITLE
Module hierarchy refactoring

### PR DESCRIPTION
**Pull request by LucaMarconato**
closes https://github.com/scverse/spatialdata/issues/103
closes https://github.com/scverse/spatialdata/issues/61
closes https://github.com/scverse/spatialdata/issues/7
closes https://github.com/scverse/spatialdata/issues/144

### CODE REVIEW

**Comment by LucaMarconato** [comment]
Closes also https://github.com/scverse/spatialdata/pull/189 and https://github.com/scverse/spatialdata/issues/61

**Comment by LucaMarconato** [comment]
I am going to create a module called `transformations` instead of the originally planned `transform`. The reason is that we will have a transform function, which will transform an element/spatialdata object and I don't want to create confusion with names. `transformations` is a module for the transformation classes, `transform` is a function that applies a transformation.

**Comment by LucaMarconato** [comment]
Minor change:
- [x] In `transform()` (the function to transform elements or sdata objects), I changed the default of `maintain_positioning` from `False` to `True`, after feedback from @EliHei2.

**Comment by LucaMarconato** [comment]
Finished 🥵 Before merging I need to make sure that `spatialdata-io`, `spatialdata-sandbox`, `spatialdata-notebooks` and `napari-spatialdata` work.

**Comment by giovp** [comment]
so have checked it out locally, will report as comments here (github is super slow at rendering it)
- remove `elements_utils`, that stuff can go in either transformations/operations or global utils.
- remove the `_constants` module, apparently it's never used
- I would remove `__main__.py` I doubt there is a single use case of that from users, but no strong feelings.

rest looks really good, thanks @LucaMarconato !

**Review by giovp — APPROVED** [review]

**Comment by LucaMarconato** [comment]
@giovp thanks for the review. 

* I have split`elements_utils` into `spatialdata.models._utils` and `spatialdata._utils`. 
* I have removed the `_constants` module.
* I kept the CLI (`__main__.py`), but I have added a docstring (so closing https://github.com/scverse/spatialdata/issues/144). I use the CLI quite a lot for quick look at the data and I think this would be a great way to interact with the tool for people not familiar with Python. Also I plan to expand the CLI functions, for instance to quickly get the extent of the data, to show the DAG of coordinate transformations and to quickly extract a downscaled version of the image (like a png) from the large zarr images. I opened an issue about these new features: https://github.com/scverse/spatialdata/issues/190

**Pull request merged**
