### PR TITLE
rechunking raster data after spatial query

### PR DESCRIPTION
**Pull request by LucaMarconato**
Rechunks the raster data (chunks are computed automatically) after a spatial query of raster data.

### CODE REVIEW

**Comment by christinedien** [comment]
Hi I was wondering when this change will be merged with the main branch? I am also querying a TMA and unable to save to .zarr because of the irregular chunks issue. where has the multi_table branch gone? Thank you!

**Comment by wakelin-g** [comment]
> Hi I was wondering when this change will be merged with the main branch? I am also querying a TMA and unable to save to .zarr because of the irregular chunks issue. where has the multi_table branch gone? Thank you!

No clue what happened to the code as I can't find it on any branch either. You can manually rechunk the images before you save. @LucaMarconato had this in an issue somewhere I just can't find it to reference now. Make sure you have the newest version of `dask`.

```{python}
def rechunk(msi):
    for scale in msi.keys();
        msi[scale]['image'] = msi[scale]['image'].chunk('auto')


sdata_query = spatialdata.polygon_query(...)
rechunk(sdata_query['morphology_mip'])
rechunk(sdata_query['morphology_focus'])
sdata_query.write('query.zarr')
```

**Comment by christinedien** [comment]
Hi thank you for the response. I did try that work around but it still fails to save as a .zarr. I also tried to downgrade dask since it worked for this person (https://github.com/scverse/spatialdata-io/issues/117#issuecomment-1996232900) but ran into many version conflict errors now that so many dask packages and dependencies have since been updated.

**Comment by christinedien** [comment]
Hi @LucaMarconato, Thank you for the response. 

I do have the most recent (non dev) release installed but am still encountering the error. The error does not happen with every subset query, but if it does it is reproducible. I have started an issue [here](https://github.com/scverse/spatialdata/issues/821)

Thank you!

**Pull request merged**
