### PR TITLE
specify n_channels

### PR DESCRIPTION
**Pull request by melonora**
This is for writing tests in napari-spatialdata where for RGB it is required to specify the number of channels.

### CODE REVIEW

**Comment by melonora** [comment]
@LucaMarconato @kevinyamauchi Could one of you review this please and then release? The test for RGB in napari-spatialdata depends on it.

**Review by kevinyamauchi — APPROVED** [review]
LGTM, thanks!

@giovp , can you please take a look? I don't understand the notebook submodule diff. Why is that showing up here? Is it just saying that the notebooks repo was updated separately and those changes will be committed here now?

**Comment by giovp** [comment]
should be good but to be extra sure @melonora could you fetch and pull from the submodule and push again with the latest version? then you shouldn't have those diffs. I think we need to add that folder to gitignore to prevent this.

**Comment by kevinyamauchi** [comment]
Thanks for the update, @melonora ! The diff now looks good. I will merge now.

**Pull request merged**
