### PR TITLE
add io test

### PR DESCRIPTION
**Pull request by giovp**

### CODE REVIEW

**Review by ivirshup — APPROVED** [review]
I'd like to merge.

Question though: Why do the test directories have names like `_io`? Idk that we need to specify private v public tests.

**Comment by giovp** [comment]
I believe @LucaMarconato merged this in #22  already, can we close it?

thanks for feedback, good point we can remove private/public

**Comment by ivirshup** [comment]
Can we merge it instead? I would much rather have the test on main.

**Comment by LucaMarconato** [comment]
Yes we can merge. I added an extra step to the roundtrip (writing back to disk and checking the written output bytewise) and this triggers a nasty bug. Gonna open a issue later, but we meanwhile we can merge this.

**Pull request merged**
