### PR TITLE
polygon_query() support for images

### PR DESCRIPTION
**Pull request by LucaMarconato**
Small PR, needed for the paper.

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
Hey @LucaMarconato. thanks for the PR!. looks like the failing test is related. Please ping me when you've fixed it and I can review.

**Comment by LucaMarconato** [comment]
Fixed now, thanks for the review. This is also a linked review please: https://github.com/scverse/spatialdata-notebooks/pull/51/files

**Review by kevinyamauchi — APPROVED** [review]
LGTM! Thanks!

**Comment by kevinyamauchi** [comment]
> Fixed now, thanks for the review. This is also a linked pr, can you also review that please? https://github.com/scverse/spatialdata-notebooks/pull/51/files

I already approved this PR a couple of days ago. Is there something else you need feedback on?

**Pull request merged**
