### PR TITLE
docs (#191)Co-authored-by: giovp <giov.pll@gmail.com>

### PR DESCRIPTION
**Pull request by LucaMarconato**
Working on the docs. 

Minor:
- [x] small fix in .flake8 file (removed reference to a file that is now deleted)

### CODE REVIEW

**Comment by giovp** [comment]
closing in favour of #192

**Comment by LucaMarconato** [comment]
wait, I restored the branch (this branch gives docs for some functions that are not in the `api.md` in main. I will merge and make a pr now.

**Comment by LucaMarconato** [comment]
@giovp I added the missing functions to the docs. Ready for review and being merged.

**Comment by giovp** [comment]
I've done some cleanup and added better docs for installation, will merge this and work on tutorials in the next one.

**Comment by giovp** [comment]
will also make separate PR to switch to ruff cause flake 8 has been very annoying lately

**Pull request merged**
