### PR TITLE
legacy code to port

### PR DESCRIPTION
**Pull request by LucaMarconato**
Merge postponed.
Before merging (an updated version of) this pr, the following will be isolated in a separate pr, improved, and merged.
- [x] coordinate systems
- [x] coordinate transformations
- [x] io branch from @giovp 

## About this pr.
This pull request implements a first working version of coordinate systems, transformations, as long as all what spatialdata needs to perform basic io operatations with its elements. Spatialdata-sandbox and napari_spatialdata support this branch. They will also need to be adapted to the new improved code described in the incremental prs listed above.

### CODE REVIEW

**Comment by kevinyamauchi** [comment]
@LucaMarconato , can this PR be closed?

**Comment by LucaMarconato** [comment]
@kevinyamauchi unfortunately not, it has features that are not merged yet. I plan to work on this over the the christmas holidays (should be 1-2 days of work).

**Comment by kevinyamauchi** [comment]
No worries, @LucaMarconato ! Just checking in to see if I needed to do anything here 😛

**Comment by LucaMarconato** [comment]
Instead of merging this branch, which is very outdated, I will pick the following and merge in multiple prs. The rest can be discarded.

  - [ ] filter_by_coordinate_system() from _spatialdata.py
  - [ ] [concatenate()](https://github.com/scverse/spatialdata/blob/1990172f788a31d58a295a383b09e84a1ad58ddb/spatialdata/_core/_spatialdata.py#L267)
  - [ ] generate multiscale from multiscale.py
  - [ ] in general check read.py and eventually port the useful elements
  - [ ] in general check write.py and eventually port the useful elements
  - [ ] main.py (which adds cli support)
  - [ ] restore links to the docs in the raedme

**Comment by LucaMarconato** [comment]
The code of this branch is [archived here](https://github.com/scverse/spatialdata/releases/tag/archive%2Finitial_prototype_coord_spaces).

**Pull request closed without merging**
